# Generated by Django 3.1.3 on 2020-12-22 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careforallapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfileInfo',
        ),
    ]
