# Generated by Django 3.1.3 on 2020-12-31 05:51

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careforallapp', '0004_post1_post2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post1',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post2',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
