# Generated by Django 3.1.3 on 2020-12-31 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careforallapp', '0005_auto_20201231_1121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post1',
            old_name='slug',
            new_name='slug1',
        ),
        migrations.RenameField(
            model_name='post2',
            old_name='slug',
            new_name='slug2',
        ),
    ]
