# Generated by Django 3.1.3 on 2020-12-31 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careforallapp', '0006_auto_20201231_1720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post1',
            old_name='author',
            new_name='author1',
        ),
        migrations.RenameField(
            model_name='post1',
            old_name='content',
            new_name='content1',
        ),
        migrations.RenameField(
            model_name='post1',
            old_name='sno',
            new_name='sno1',
        ),
        migrations.RenameField(
            model_name='post1',
            old_name='timeStamp',
            new_name='timeStamp1',
        ),
        migrations.RenameField(
            model_name='post1',
            old_name='title',
            new_name='title1',
        ),
        migrations.RenameField(
            model_name='post2',
            old_name='author',
            new_name='author2',
        ),
        migrations.RenameField(
            model_name='post2',
            old_name='content',
            new_name='content2',
        ),
        migrations.RenameField(
            model_name='post2',
            old_name='sno',
            new_name='sno2',
        ),
        migrations.RenameField(
            model_name='post2',
            old_name='timeStamp',
            new_name='timeStamp2',
        ),
        migrations.RenameField(
            model_name='post2',
            old_name='title',
            new_name='title2',
        ),
    ]
