# Generated by Django 3.1.3 on 2021-01-04 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post1',
            new_name='Post',
        ),
    ]
